export interface Question {
  id: number
  question: string
  options: {
    a: string
    b: string
    c: string
  }
  optionImages?: {
    a?: string
    b?: string
    c?: string
  }
  correct: "a" | "b" | "c"
  hasImage?: boolean
  image?: string // Changed from imageNote to image for clarity with the update
}

export interface QuestionSet {
  id: string
  name: string
  description: string
  questions: Question[]
}

// Helper function to create question objects
const q = (id: number, question: string, a: string, b: string, c: string, correct: "a" | "b" | "c"): Question => ({
  id,
  question,
  options: { a, b, c },
  correct,
})

// Helper for questions with an image in the question
const qWithImage = (
  id: number,
  question: string,
  a: string,
  b: string,
  c: string,
  correct: "a" | "b" | "c",
  image: string,
): Question => ({
  id,
  question,
  options: { a, b, c },
  correct,
  hasImage: true,
  image,
})

// Helper for questions with image answers
const qWithImageAnswers = (
  id: number,
  question: string,
  correct: "a" | "b" | "c",
  optionImages: {
    a?: string
    b?: string
    c?: string
  },
  questionImage?: string,
): Question => ({
  id,
  question,
  options: {
    a: "",
    b: "",
    c: "",
  },
  optionImages,
  correct,
  hasImage: !!questionImage,
  image: questionImage,
})

// All question sets with correct data from PDF
export const questionSets: QuestionSet[] = [
  {
    id: "set1",
    name: "Reeks 1",
    description: "",
    questions: [
      q(
        1,
        "Hoeveel bedraagt de voortplantingssnelheid van elektromagnetische golven?",
        "300.000 km/s",
        "300.000 m/s",
        "300.000.000 km/s",
        "a",
      ),
      q(
        2,
        "Hoe noemen we het aantal golven dat per seconde wordt opgewekt?",
        "Golflengte",
        "Frequentie",
        "Amplitude",
        "b",
      ),
      q(
        3,
        "Waaraan is één Hertz gelijk?",
        "10.000 golven per seconde",
        "1.000 golven per seconde",
        "1 golf per seconde",
        "c",
      ),
      q(
        4,
        "Waaraan is het product van frequentie en golflengte gelijk? (frequentie X golflengte = ?)",
        "Voortplantingssnelheid",
        "Amplitude",
        "Golfperiode",
        "a",
      ),
      q(
        5,
        "Gegeven: de frequentie van de elektromagnetische golven bedraagt 10.000 Mhz. Gevraagd: bereken de golflengte",
        "3.1 cm",
        "30 cm",
        "3 cm",
        "c",
      ),
      q(
        6,
        "Hoe wordt de afstand tussen de plaats van uitzending en het waargenomen voorwerp bepaald?",
        "Afstand tussen de voorwerpen meten en delen door twee",
        "Tijd meten van de zendimpuls en delen door twee",
        "Door de tijd te meten die verstrijkt tussen uitzenden van een impuls en het binnenkomen van een echo. Dit gebeurt in het radartoestel",
        "c",
      ),
      q(
        7,
        "Gegeven: tijd tussen uitzending en ontvangst van de elektromagnetische golven is 60 microseconden. Gevraagd: bereken de afstand?",
        "18.000 m",
        "900 m",
        "9.000 m",
        "c",
      ),
      q(
        8,
        "Duid de fout aan.",
        "Hoek van inval = hoek van uitval",
        "Het afstandsonderscheidingsvermogen is gelijk aan de halve impulslengte",
        "Als de invalshoek 135° bedraagt, krijgen we een goede echo",
        "c",
      ),
      q(
        9,
        "Een rond voorwerp kan ook door de radar waargenomen worden. Hoe verklaar je dit?",
        "Op een rond voorwerp zal altijd wel ergens een goede invalshoek zijn",
        "Een rond voorwerp wordt nooit waargenomen",
        "Een rond voorwerp wordt alleen waargenomen vanuit een benedenstroomse richting",
        "a",
      ),
      q(
        10,
        "Waarom worden reflectoren gebruikt?",
        "Omdat ze in alle omstandigheden een gunstige invalshoek garanderen",
        "Omdat ze beter kunnen bevestigd worden",
        "Alleen actieve versterkers zijn nuttig",
        "a",
      ),
      q(
        11,
        "Welk nadeel is verbonden aan een beeld dat constant is afgeregeld met te veel helderheid?",
        "De zender wordt constant overbelast",
        "De gebruiker wordt beïnvloed door te veel schadelijke stralen",
        "De beeldbuis zal te vlug verslijten",
        "c",
      ),
      q(
        12,
        "Wat duidt de koersflits aan?",
        "De voorligging van het schip",
        "De vaarrichting van het schip",
        "De stand van de antenne",
        "a",
      ),
      q(
        13,
        "Wat verstaat men onder een dode zone?",
        "Een sector waarin, door omstandigheden, geen echo's in beeld kunnen komen",
        "Een gebied waarin echo's zeer zwak in beeld verschijnen",
        "Een zone waarin afgeschermde objecten toch in beeld kunnen komen",
        "a",
      ),
      q(
        14,
        "Waarom moet de verticale bundelbreedte vrij groot zijn?",
        "Anders zou men geen tonnen afgescheiden op het scherm zien",
        "De grootte van de bundel is niet belangrijk voor de waarneming",
        "Anders zou de dode hoek in de omgeving van het schip te groot zijn",
        "c",
      ),
      q(
        15,
        "Welke onderstaande redenering is, met betrekking tot de horizontale bundelbreedte, fout?",
        "Hoe breder de bundel, hoe breder de echo",
        "Hoe smaller de bundel, hoe smaller de echo",
        "De horizontale bundelbreedte heeft alleen betrekking op het afstandsonderscheidingsvermogen",
        "c",
      ),
      q(
        16,
        "Waar is de echo van een voorwerp het grootst?",
        "Aan de rand van het scherm",
        "Als het voorwerp kortbij is",
        "Er is geen onderscheid",
        "a",
      ),
      q(
        17,
        "Hoe evolueert de peiling van twee schepen die evenwijdig en aan dezelfde snelheid varen?",
        "Ze blijft onveranderd",
        "Ze verkleint",
        "Ze vergroot",
        "a",
      ),
      q(
        18,
        "Hoe evolueert de peiling genomen door een schip dat opgelopen wordt?",
        "Ze blijft onveranderd",
        "Ze verkleint",
        "Ze vergroot",
        "b",
      ),
      q(
        19,
        "Met welke breedte komt 1° van de cirkelboog, op een afstand van 1.600 m, overeen?",
        "+ / - 28 m",
        "+ / - 7 m",
        "+ / - 15 m",
        "a",
      ),
      q(
        20,
        "Hoe lang zal het duren om een schip volledig rond (360°) te laten draaien als de bochtaanwijzer 60° / min aangeeft?",
        "1 minuut",
        "3 minuten",
        "6 minuten",
        "c",
      ),
      q(
        21,
        "We peilen een tegenligger tegenover onze koersflits. Welke van onderstaande redeneringen is fout?",
        "Hoe groter de peilingshoek, hoe groter de dwarse afstand",
        "Hoe kleiner de peilingshoek, hoe kleiner de dwarse afstand",
        "De peilingshoek geeft geen sluitende indicatie met betrekking bot de dwarse afstand tussen beide schepen",
        "c",
      ),
      q(
        22,
        "Wat verstaat men onder de blinde sector of dode zone?",
        "De straal rond de scanner, waarbinnen geen echo's kunnen ontvangen worden omdat objecten gelegen zijn boven de bovenste grens van de verticale bundel",
        "De straal rond de scanner, waarbinnen geen echo's kunnen ontvangen worden omdat objecten gelegen zijn onder de onderste grens van de verticale bundel",
        "De zones die door bepaalde objecten worden afgeschermd en hierdoor geen echo's kunnen bevatten",
        "b",
      ),
      q(
        23,
        "Wat is het voordeel van een kleine horizontale bundelhoek?",
        "Het peilingonderscheidingsvermogen zal dan ook klein zijn",
        "Het peilingonderscheidingsvermogen zal dan ook groot zijn",
        "Het peilingonderscheidingsvermogen zal dan ook steeds gelijk blijven",
        "b",
      ),
      q(
        24,
        "Duid de fout aan.",
        "Het beeldscherm van een rivierradar moet minstens een diameter hebben van 30 cm",
        "Een horizontale bundelbreedte van 1° is niet toegelaten",
        "Er gelden geen voorschriften met betrekking tot de bundelbreedte",
        "c",
      ),
      q(
        25,
        "Waaraan is het afstandonderscheidingsvermogen gelijk?",
        "Aan de helft van de golflengte",
        "Aan de helft van de impulslengte",
        "Aan de helft van de amplitude",
        "b",
      ),
      q(
        26,
        "Duid de fout aan.",
        "Het beeldscherm is een lichtgebogen vlak van een anodestraalbuis",
        "De binnengekomen echo's worden in de ontvanger versterkt",
        "Als het radartoestel werkt, wordt door de kathode een fijne elektronenbundel uitgezonden",
        "a",
      ),
      q(
        27,
        "Wat is een peilingvergroting of azimuthale vergroting?",
        "De vergroting van een echo naarmate hij zich meer naar het centrum toe verplaatst",
        "De peiling van een echo die zich in wijzerzin verplaatst",
        "De vergroting van een echo naarmate hij zich meer van het centrum verwijdert",
        "c",
      ),
      q(
        28,
        "Hoe ligt de schaalverhouding bij een schaalbereik van 1.600 m?",
        "1 / 25.000",
        "1 / 12.500",
        "1 / 10.666",
        "c",
      ),
      q(
        29,
        "Hoe gedraagt de echo van een hoogspanningskabel zonder reflectoren zich in beeld, welke schuin over de vaarweg is gespannen en door je schip wordt benadert?",
        "De echo heeft het vaargedrag van een tegenligger",
        "De echo steekt de vaarweg geheel of gedeeltelijk over",
        "De echo zal altijd recht op u af komen",
        "c",
      ),
      q(
        30,
        "Waaraan moeten we vooral aandacht besteden, als we bij regenvlagen de regenonderdrukker gebruiken?",
        "Dat we de versterking iets verminderen",
        "Dat we de echo's van tonnen in de omgeving ook niet onderdrukken",
        "Dat we bij vergissing de golvenonderdrukker niet gebruiken",
        "b",
      ),
      q(31, "Geef de eenheid van frequentie?", "Volt", "Hertz", "Ampère", "b"),
      q(
        32,
        "Hoeveel tijd verstrijkt gedurende twee omwentelingen als de antenne 24 omwentelingen per minuut maakt?",
        "3 seconden",
        "2,5 seconden",
        "5 seconden",
        "c",
      ),
      q(
        33,
        "Golven die zich door de atmosfeer bewegen zijn onderhevig aan wrijving. Wat gebeurt er met de golflengte van de uitgezonden golven?",
        "De golflengte zal verkleinen",
        "De golflengte zal vergroten",
        "De golflengte blijft onveranderd",
        "c",
      ),
      q(
        34,
        "Werkend op een grote range, biedt een grote impulslengte voordelen.",
        "Deze bewering is fout",
        "Deze bewering is deels juist, deels fout",
        "Deze bewering is juist",
        "c",
      ),
      q(
        35,
        "Van welk onderdeel is de goede werking van de bochtaanwijzer sterk afhankelijk?",
        "De tol",
        "Het elektrisch circuit",
        "De analoge of digitale indicatie",
        "a",
      ),
      q(
        36,
        "Hoeveel bedraagt het afstandsonderscheidingsvermogen bij een impulsduur van 0,10 microseconden?",
        "7,5 m",
        "30 m",
        "15 m",
        "c",
      ),
      q(
        37,
        "Wat gebeurt er met de elektronen nadat ze de fluorescerende laag van het scherm getroffen hebben?",
        "Zij weerkaatsen op de binnenzijde van het beeldscherm",
        "Zij worden teruggevoerd naar de kathode",
        "Zij gaan over in licht en worden direct nadien vernietigd",
        "b",
      ),
      q(38, "Hoe is de kleinst mogelijke puntgrootte?", "1,5 vierkante mm", "0,5 vierkante mm", "2 vierkante mm", "a"),
      q(
        39,
        "Hoeveel meter bedraagt het afstandsonderscheidingsvermogen van een rivierradar?",
        "7,5 meter",
        "3,5 meter",
        "15 meter",
        "a",
      ),
      q(40, "Hoeveel microseconden telt één seconde", "1.000", "100.000", "1.000.000", "c"),
      q(
        41,
        "Waarom worden de bewegingen van echo's op het radarbeeld van ons varend schip relatief genoemd?",
        "Omdat het niet noodzakelijk allemaal ware echo's zijn",
        "Dit hangt af van de plaats en de draaisnelheid van de antenne",
        "Omdat de bewegingen van de echo's onder invloed zijn van de vaarrichting en vaarsnelheid van ons eigen varend schip",
        "c",
      ),
      q(
        42,
        "Hoeveel bedraagt de draaisnelheid van een rivierradarantenne?",
        "Ongeveer één omwenteling per drie seconden",
        "Ongeveer twee omwentelingen per seconden",
        "Ongeveer twee omwentelingen per vijf seconden",
        "c",
      ),
      q(
        43,
        'Welk geluidssein geeft een schip dat "achteruitslaat"?',
        "Drie korte stoten",
        "Twee korte stoten",
        "Eén korte stoot",
        "a",
      ),
      q(
        44,
        "Waarom verkleint men bij het naderen van een brug beter het schaalbereik?",
        "Men vergroot de kans dat de brugpeilers beter zichtbaar worden",
        "Men kan dan steeds, geheel of gedeeltelijk, onder de brug door kijken",
        "Men kan dan nauwkeuriger de afstand tot de brug meten",
        "a",
      ),
      q(
        45,
        "Hoe versterkt men echo's?",
        'Door de knop "versterking" of "gain" naar rechts te draaien',
        'Door de knop "regenonderdrukker" of "A/C rain" naar rechts te draaien',
        'Door de knop "helderheid" of "brilliance" naar links te draaien',
        "a",
      ),
      q(46, "Op welke band zendt een rivierradar uit?", "3 cm of S-band", "3 cm of X-band", "10 cm of S-band", "b"),
      q(
        47,
        "Wanneer wordt de elektronenstraal in de beeldbuis doorgelaten?",
        "Zodra en zolang er een echo ontvangen wordt",
        "Alleen als de afstemmingsknop optimaal is afgeregeld",
        "Gedurende de volledige ontvangsttijd",
        "a",
      ),
      q(
        48,
        "Hoeveel heeft een schip nodig om te keren (180°) als de draaisnelheid 45° / min. bedraagt?",
        "8 minuten",
        "4 minuten",
        "2 minuten",
        "b",
      ),
      q(
        49,
        "Je wil bakboord opdraaien. Welk geluidssein zal je geven?",
        "Eén lange stoot gevolgd door één korte",
        "Eén lange stoot gevolgd door twee korte",
        "Eén lange stoot gevolgd door drie korte",
        "b",
      ),
      q(
        50,
        "Waaraan is een valse echo vaak te herkennen?",
        "Hij heeft steeds een abnormale vorm en grootte",
        "Hij verdwijnt even plots uit het beeld als hij er in verschijnt",
        "Hij is steeds veel zwakker dan de ware echo's",
        "b",
      ),
    ],
  },
  {
    id: "set2",
    name: "Reeks 2",
    description: "",
    questions: [
      q(
        51,
        "Waaruit is een radarimpuls samengesteld?",
        "Een serie aan elkaar gekoppelde radioactieve golven",
        "Een serie aan elkaar gekoppelde elektromagnetische golven",
        "Een serie aan elkaar gekoppelde elektromechanische golven",
        "b",
      ),
      q(
        52,
        "Wat is het afstandsonderscheidingsvermogen?",
        "Het vermogen om de afstand te meten tussen twee verschillende echo's",
        "Het vermogen om twee voorwerpen die op dezelfde peiling liggen als aparte echo's in beeld te krijgen",
        "Het vermogen om de correcte afstand te meten met behulp van de variabele afstandsring",
        "b",
      ),
      q(
        53,
        "Op welke wijze geef je een aandachtssein?",
        "Door drie lange stoten te geven",
        "Door twee lange stoten te geven",
        "Door één lange stoot te geven",
        "c",
      ),
      q(
        54,
        "Wanneer zal een genomen bocht het kortst zijn of draait men zelfs ter plaatse?",
        "Als de vaarsnelheid en de hoeksnelheid groot zijn",
        "Als de vaarsnelheid laag en de hoeksnelheid groot is",
        "Als de vaarsnelheid groot en de hoeksnelheid klein is",
        "b",
      ),
      q(
        55,
        "Een echo van een hoogspanningskabel beweegt over het radarscherm van rechts naar links. We veranderen onze vaarrichting met als gevolg dat de echo stil staat. Naar welke zijde zijn we van vaarrichting veranderd?",
        "Naar bakboord",
        "Naar stuurboord",
        "Achteruit",
        "b",
      ),
      q(
        56,
        "Welke garanties geeft een goed werkende bochtaanwijzer die tijdens de vaart 0° / min aangeeft?",
        "Dat het schip de geplande koers over de grond volgt",
        "Dat de voorligging van het schip onveranderd blijft",
        "Dat de koers niet wordt beïnvloedt door de stroom noch door de wind",
        "b",
      ),
      q(
        57,
        'Wanneer vaart een schip "met behulp van radar"?',
        "Zodra er een radartoestel aan boord staat",
        "Wanneer de radarwaarnemer navigeert door middel van alleen de informatie die door de radar verstrekt wordt",
        'Wanneer de radarwaarnemer navigeert door middel van de informatie verkregen door het radartoestel gecombineerd met de informatie "op zicht"',
        "b",
      ),
      q(
        58,
        "Waarom kan men niet juist peilen met een gedecentreerd beeld van een radartoestel waarvan het beeldscherm noch de gradenverdeling is aangepast?",
        "Men kan wel juist peilen",
        "Men moet het verschil berekenen",
        "Omdat het middelpunt verschoven is",
        "c",
      ),
      q(59, "Welke golflengte gebruikt een rivierradar?", "0,3 m", "0,03 m", "0,003 m", "b"),
      q(60, "Waarvan is de impulslengte afhankelijk?", "De zendtijd", "De ontvangsttijd", "De repetentie", "a"),
      q(
        61,
        'Wanneer vaart een schip "op radar"?',
        "Als het zicht beperkt is",
        "Als de radar in gebruik is",
        "Het vaart op alleen de waarnemingen van het radarbeeld",
        "c",
      ),
      q(
        62,
        "Twee schepen varen evenwijdig aan elkaar. Het schip dat stuurboord vaart stopt plots af terwijl het bakboord varend zijn kruissnelheid aanhoudt. Hoe zullen de boegpeilingen, gemaakt door het bakboord varend schip evolueren?",
        "Ze zullen vergroten",
        "Ze blijven gelijk",
        "Ze zullen verkleinen",
        "a",
      ),
      q(
        63,
        "Twee schepen varen evenwijdig aan elkaar. Het schip dat bakboord vaart stopt plots af terwijl het stuurboord varend zijn kruissnelheid aanhoudt. Hoe zal de echo van het bakboord varend schip evolueren in het radarbeeld van het stuurboord varend schip?",
        "De echo zal vergroten",
        "De grootte van de echo blijft gelijk",
        "De echo zal verkleinen",
        "a",
      ),
      q(
        64,
        "Welke informatie verschaft een radarbeeld?",
        "Karakteristieken en eigenschappen van echo's",
        "Aard en grootte van echo's",
        "Peiling en afstand van echo's",
        "c",
      ),
      q(
        65,
        "Kan, bij bepaalde schaalbereiken (Range) een echo verlengd of vergroot worden?",
        "Dit kan nooit",
        "Dit kan door de impulslengte te vergroten (van short naar long pulse)",
        "Dit kan door de impulslengte te verkleinen (van long naar short pulse)",
        "b",
      ),
      q(
        66,
        "Wat is de functie van de magnetron in het radartoestel?",
        "Het is de zender die de radargolven opwekt",
        "Hij bundelt de elektronenstraal",
        "Hij regelt het verkeer tussen zenden en ontvangen",
        "a",
      ),
      q(
        67,
        "Hoe onderscheidt men de ware echo van de meervoudige echo's?",
        "De verst verwijderde echo is steeds de ware echo",
        "De dichts bij gelegen echo is steeds de ware echo",
        "De grootste echo is steeds de ware echo",
        "b",
      ),
      q(68, "Wat stelt de koersflits voor?", "De voorligging", "Het ware noorden", "Het kompasnoorden", "a"),
      q(
        69,
        "Met welk principe werkt de bochtaanwijzer?",
        "Het principe van de stethoscoop",
        "Het principe van de gyroscoop",
        "Het principe van de telescoop",
        "b",
      ),
      q(70, "Onder welke invalshoek worden radargolven weerkaatst richting scanner?", "90°", "80°", "70°", "a"),
      q(
        71,
        "Wat wordt verstaan onder de Lambda-band?",
        "De golflengte die bij zeeradars wordt gebruikt",
        "De golflengte die bij rivierradars wordt gebruikt",
        "De golflengte die bij kustradars wordt gebruikt",
        "b",
      ),
      q(
        72,
        "Wanneer spreken we gegarandeerd over een reëel beeld?",
        "Bij een gemeerd schip",
        "Bij een schip dat vaart door het water loopt",
        "Bij een schip dat vaart over de grond loopt",
        "a",
      ),
      q(
        73,
        "Hoe ontstaat een dode zone of schaduwzone?",
        "Door afscherming van de golvenbundel door delen van het eigen schip",
        "Door golfslag",
        "Door atmosferische storingen",
        "a",
      ),
      q(
        74,
        'Wat verstaat men onder de uitdrukking "North-up"?',
        "De koersflits wijst de voorligging aan ten opzichte van het Noorden",
        "De koersflits wijst het Noorden aan",
        "De koersflits wijst een voorligging aan die niet gerelateerd is aan het Noorden",
        "a",
      ),
      q(
        75,
        'Wat verstaat men onder de uitdrukking "Ship\'s head-up"?',
        "De koersflits geeft de vaarrichting aan",
        "De koersflits geeft de mogelijke drift aan",
        "De koersflits geeft de voorligging aan en is recht naar boven gericht",
        "c",
      ),
      q(
        76,
        'Een schip wil "kop voor nemen" en wijzigt zijn koers tegen een draaisnelheid van 30° / min. In hoeveel seconden zal zijn koers 180° veranderd zijn?',
        '90"',
        '180"',
        '360"',
        "c",
      ),
      q(
        77,
        "Een varend schip heeft een ander in de peiling. De peiling zal steeds veranderen, behalve in één situatie. Welke situatie?",
        "Als het andere schip gestopt ligt",
        "Als beide schepen een evenwijdige koers en gelijke snelheid aanhouden",
        "Als het andere schip een oploper is",
        "b",
      ),
      q(
        78,
        "De doorvaartopening van een brug komt in beeld. Hoeveel bedraagt de breedte van deze opening als we ze peilen onder een hoek van 6° op een afstand van precies 600 m?",
        "36 meter",
        "60 meter",
        "100 meter",
        "b",
      ),
      q(
        79,
        "Twee boeien liggen beide op een afstand van 600 meter van de radarantenne. Hun onderlinge afstand bedraagt 80 meter. Hoe zullen we de echo's van deze boeien ontvangen?",
        "Als twee aparte echo's",
        "Als één samengevloeide echo",
        "We ontvangen ze niet",
        "a",
      ),
      q(
        80,
        "Welk soort bochtaanwijzer vraagt een log of traag manoeuvreerbaar schip?",
        "Een bochtaanwijzer met trage indicatie",
        "Een bochtaanwijzer met middelmatige indicatie",
        "Een bochtaanwijzer met snelle indicatie",
        "c",
      ),
      q(
        81,
        "Welk soort bochtaanwijzer vraagt een makkelijk wendbaar schip?",
        "Een bochtaanwijzer met trage indicatie",
        "Een bochtaanwijzer met middelmatige indicatie",
        "Een bochtaanwijzer met snelle indicatie",
        "a",
      ),
      q(
        82,
        "Welk soort bochtaanwijzer vraagt een middelmatig wendbaar schip?",
        "Een bochtaanwijzer met trage indicatie",
        "Een bochtaanwijzer met middelmatige indicatie",
        "Een bochtaanwijzer met snelle indicatie",
        "b",
      ),
      q(83, "De verticale bundelhoek ligt tussen:", "15° en 30°", "5° en 15°", "25° en 35°", "a"),
      q(
        84,
        "De verticale bundelhoek wordt bepaald met als doel:",
        "lage objecten, bij een slingerend en stampend vaartuig, niet te missen",
        "een grotere en bijgevolg beter zichtbare echo te bekomen",
        "een duidelijke en scherpe echo van kleine vaartuigen te bekomen",
        "a",
      ),
      q(
        85,
        "De horizontale bundelhoek van een rivierradarimpuls is:",
        "tussen de 0,4° en 1,2°",
        "tussen de 5° en 10°",
        "tussen de 15° en 25°",
        "a",
      ),
      q(
        86,
        "De horizontale bundelhoek wordt bepaald met als doel:",
        "een zo juist mogelijke richting van een voorwerp te kunnen bepalen",
        "het zendvermogen zo klein mogelijk te houden",
        "zoveel mogelijk energie in de bundel te kunnen uitzenden",
        "a",
      ),
      q(
        87,
        "Het afstandsonderscheidingsvermogen is afhankelijk van:",
        "de azimuthale vervorming",
        "de impulslengte",
        "de draaisnelheid van de antenne",
        "b",
      ),
      q(
        88,
        "Men noemt afstandsonderscheidingsvermogen",
        "het vermogen om twee, in dezelfde peiling en op korte afstand van elkaar liggende voorwerpen, toch afzonderlijke echo's in beeld te krijgen",
        "het vermogen om de afstand van voorwerp tot voorwerp te meten",
        "het vermogen om met radar de afstand van waargenomen voorwerpen te meten",
        "a",
      ),
      q(
        89,
        "Men noemt het peilingonderscheidingsvermogen",
        "de mogelijkheid van de radar om de richting van voorwerpen te bepalen",
        "het vermogen om met radar de koers van het schip te berekenen",
        "het vermogen om twee objecten die beide op gelijke afstand van de scanner gelegen zijn, toch als aparte echo's in beeld te krijgen",
        "c",
      ),
      q(
        90,
        "Hoe groot is de golflengte en van welk band wordt bij een rivierradar gebruik gemaakt?",
        "30 cm of U-band",
        "3 cm of X-band",
        "3 cm of Z-band",
        "b",
      ),
      q(
        91,
        "De rivierradar verschaft de waarnemer twee belangrijke informaties:",
        "richting en afstand van het waargenomen schip tot het eigen schip",
        "de afstand en de grootte van het gedetecteerde schip",
        "vorm en grootte van het waargenomen schip",
        "a",
      ),
      q(
        92,
        "Welke golven worden door een radartoestel gebruikt?",
        "Hoge geluidsgolven",
        "Elektromagnetische golven",
        "Ultraviolet golven",
        "b",
      ),
      q(
        93,
        "De echo's van twee voorwerpen die op gelijke afstand van de scanner gelegen zijn, komen slechts apart in beeld als de onderlinge afstand groter is dan de horizontale bundelbreedte ter plaatse",
        "Juist",
        "Fout",
        "Als men geen twee aparte echo's ziet moet men het beeld beter afstellen",
        "a",
      ),
      q(94, "VRM betekent:", "Variable Ring Marker", "Variable Range Marker", "Variable Range Modulation", "b"),
      q(
        95,
        "De afstand tussen het punt dat op het radarscherm de scanner voorstelt en de eerste vaste afstandsring is gelijk aan de afstand tussen de andere vaste afstandsringen",
        "Juist",
        "Fout",
        "Hangt af van het ingestelde schaalbereik",
        "a",
      ),
      q(
        96,
        "De minimum reikwijdte van de radar hangt af van:",
        "de verticale bundelhoek",
        "de verticale bundelhoek en de opstelling van de antenne tegenover de scheepsopbouw",
        "de verticale bundelhoek, de opstelling van de antenne tegenover de scheepsopbouw en van de impulsduur",
        "c",
      ),
      q(
        97,
        "De door het radartoestel uitgezonden impulsen,",
        "worden altijd teruggekaatst door voorwerpen en ook steeds ontvangen",
        "worden slechts teruggekaatst via dezelfde weg als de golven loodrecht op het metalen voorwerp terechtkomen",
        "worden alleen teruggekaatst als ze metalen voorwerpen raken",
        "b",
      ),
      q(
        98,
        "Als de elektromotor (rotor) die de radarantenne doet draaien, zou stoppen terwijl het radartoestel zelf normaal blijft werken",
        "dan zal men op het radarscherm slechts de echo's kunnen waarnemen van de voorwerpen die zich in de richting bevinden waarin de antenne uitzendt",
        "dan kan men geen afstanden meer bepalen",
        "dan blijft het beeld op het radarscherm ongewijzigd, dus net zoals het was vóór het stoppen van de motor",
        "a",
      ),
      q(
        99,
        "Onder nalichting van het scherm verstaat men:",
        "het verschijnen van spookecho's op het scherm",
        "het verschijnsel dat de echolichtvlekjes op het scherm enige tijd zichtbaar blijven",
        "de tijd, na het aanzetten van het toestel, nodig om beeld te krijgen",
        "b",
      ),
      q(
        100,
        "De versterkingsknop van het radartoestel heeft volgende functie:",
        "hij regelt de lichtsterkte van de echo's op het scherm",
        "hij regelt het zendvermogen",
        "hij regelt het zendvermogen van de zender",
        "c",
      ),
    ],
  },
  {
    id: "set3",
    name: "Reeks 3",
    description: "",
    questions: [
      q(
        101,
        "De dode zone is:",
        "het gebied dat verder ligt dan het gekozen schaalbereik",
        "het gebied onder de verticale bundel",
        "het gebied dwars aan SB en BB van het schip",
        "b",
      ),
      q(
        102,
        "Spookecho's zijn afkomstig van:",
        "meervoudige onregelmatige terugkaatsingen tussen meestal op de oever van de vaarweg gelegen grote gebouwen",
        "kleine vaartuigen die ten gevolge van golven niet steeds geraakt worden door de impulsen",
        "hoogspanningskabels",
        "a",
      ),
      q(
        103,
        'De knop "helderheid"',
        "moet zo ver opengedraaid worden tot men de koersflits ziet",
        "werkt automatisch",
        "moet zo ver mogelijk opengedraaid worden",
        "a",
      ),
      q(
        104,
        "Hoe gaat men, aan boord van een varend schip, na of een geobserveerde echo al dan niet van een varend schip is?",
        "Men neemt een peiling, als de peiling verandert is het schip niet in beweging",
        "men let op de grote van de echo",
        "men gaat na of de echo van dat vaartuig zich verplaatst ten opzichte van vaste punten aan land",
        "c",
      ),
      q(
        105,
        'De presentatie "Ship\'s head-up" betekent:',
        "alle echo's op het scherm verschijnen in functie van het ware Noorden",
        "alle echo's op het scherm verschijnen in functie van de voorligging van het eigen schip",
        "alle echo's op het scherm verschijnen in functie van het magnetische Noorden",
        "b",
      ),
      q(
        106,
        'Met de "golfstoringsonderdrukker" en de "neerslagstoringsonderdrukker"',
        "worden alleen de hinderlijke echo's van golven en neerslag verzwakt",
        "worden benevens de hinderlijke echo's van golven en neerslag ook nog andere echo's verzwakt",
        "worden geen echo's verzwakt, wel de gevolgen en de regen",
        "b",
      ),
      q(
        107,
        "De theoretische minimumreikwijdte is gelijk aan:",
        "de helft van de afstand die door de golven wordt afgelegd tijdens de duur van één zendimpuls",
        "3 cm bij een 3 cm radar en 10 cm bij een 10 cm radar",
        "de afstand die door de golven wordt afgelegd tijdens de duur van één zendimpuls",
        "a",
      ),
      q(
        108,
        "De nalichtingstijd bij een klassiek doch goed werkend beeldscherm is:",
        "korter dan de tijd welke de radarantenne nodig heeft voor het maken van één omwenteling",
        "lang bij een oud toestel en kort bij een nieuw toestel",
        "groter dan de tijd welke een radarantenne nodig heeft voor het maken van één omwenteling",
        "c",
      ),
      q(
        109,
        "Als de relatieve afstand, in 3 minuten afgelegd door een echo 1 zeemijl bedraagt, met hoeveel knopen komt dan de relatieve snelheid van deze echo overeen?",
        "20 knopen",
        "25 knopen",
        "15 knopen",
        "a",
      ),
      q(
        110,
        "De echo van een boei is:",
        "een vierkante stip als deze boei op een grote afstand gelegen is",
        "steeds een ronde echo",
        "een dwarsliggend streepje indien de boei op een grote afstand ligt",
        "a",
      ),
      q(
        111,
        "Zandbanken en vlakke oevers geven:",
        "nooit echo's op het radarscherm",
        "geen of zwakke echo's op het radarscherm",
        "geen echo's van droge oevers of droge zandbanken",
        "b",
      ),
      q(
        112,
        "U vaart in een rechte kanaalarm, evenwijdig aan de kade. Hoogspanningskabels overspannen dit vaarwater onder een hoek van 90°. Waar zal eventueel de ware echo van de hoogspanningskabel zichtbaar zijn?",
        "Aan SB-zijde van de koersflits",
        "Aan BB-zijde van de koersflits",
        "Op de koersflits",
        "c",
      ),
      q(
        113,
        "Varend in de mist proberen we een aanvaring te vermijden. Hiervoor moeten we uitwijken tegen een draaisnelheid van 30° / min. We zullen als volgt te werk gaan:",
        "we gaan in één stap van 0° / min naar 30° / min",
        "we gaan in twee stappen van elk 15° / min",
        "we gaan in drie stappen van elk 10° / min",
        "a",
      ),
      q(
        114,
        "Twee boeien van gelijke grote liggen op dezelfde peiling en op een onderlinge afstand van 500 meter:",
        "beide boeien geven een even grote echo",
        "de boei die het verst weg ligt geeft een kleinere echo dan de boei die het kortst bij ligt",
        "de boei die het verst weg ligt geeft een grotere echo dan de boei die het kortst bij ligt",
        "c",
      ),
      q(
        115,
        'Wat is een "RACON":',
        "een boei voorzien van een radarreflector",
        "een baken dat zelf regelmatig radargolven uitzendt met als doel een speciale echo op het radarscherm van de waarnemer te veroorzaken",
        "een baken dat reageert op de energie die door onze radar wordt uitgezonden en samen met de echo van het baken zelf, een speciale echo veroorzaakt in beeld",
        "c",
      ),
      q(
        116,
        "We zijn varend terwijl we regelmatig peilingen nemen van een ander vaartuig, de peiling verandert niet. Dit betekent:",
        "er is altijd aanvaringsgevaar",
        "er is aanvaringsgevaar als bovendien ook de afstand verkleint",
        "radarpeilingen hebben geen belang bij het bepalen van aanvaringsgevaar",
        "b",
      ),
      q(
        117,
        "Twee vaartuigen varen op gelijke koers en met gelijke snelheid.",
        "Peilingen zullen na enige tijd veranderen",
        "Peilingen blijven steeds gelijk",
        "Door de geringe nalichting kunnen niet altijd peilingen gemaakt worden",
        "b",
      ),
      q(
        118,
        "Twee schepen varen op een evenwijdige koers en met gelijke snelheid. Het schip dat het andere aan zijn SB-zijde waarneemt, stopt zijn machine. De boegpeiling van het vaartuig dat hij observeert wordt:",
        "groter",
        "kleiner",
        "blijft onveranderd",
        "b",
      ),
      q(
        119,
        "Men vaart evenwijdig aan een kaaimuur. Van deze kaaimuur ontvangt je op het scherm meerdere echo's waarvan de onderlinge afstand gelijk is. Welke bewering is juist?",
        "De ware echo is deze die het dichtst bij je schip gelegen is",
        "De ware echo is deze die het verst van je schip gelegen is",
        "Een kaaimuur kan nooit meervoudige echo's veroorzaken",
        "a",
      ),
      q(
        120,
        "De afdekplaat van de radarantenne mag niet geschilderd worden omdat:",
        "de radargolven dan afgebogen worden en zich niet meer in de juiste richting voortplanten",
        "de verf de straling zou kunnen opslorpen of tegenhouden",
        "dit zeer schadelijk is voor het radartoestel zelf",
        "b",
      ),
      q(
        121,
        "Schroefwater van een geobserveerd vaartuig,",
        "kan op het radarscherm zichtbaar worden bij kalm wateroppervlak",
        "kan slechts vastgesteld worden met een zeeradar",
        "kan nooit met een radar waargenomen worden",
        "a",
      ),
      q(
        122,
        "Een schip dat vooraan door de impuls wordt geraakt, geeft",
        "in bepaalde gevallen twee gescheiden echo's",
        "nooit twee gescheiden echo's",
        "snelvarend: één echo, traag varend: twee echo's",
        "a",
      ),
      q(
        123,
        "Twee voorwerpen die op dezelfde afstand van de antenne liggen en waarvan het peilingverschil klein is, worden",
        "steeds als twee afzonderlijke echo's op het scherm waargenomen",
        "slechts als twee afzonderlijke echo's waargenomen als het toestel optimaal is afgeregeld",
        "enkel als twee afzonderlijke echo's waargenomen als hun onderlinge afstand groter is dan de horizontale bundelbreedte ter hoogte van de voorwerpen",
        "c",
      ),
      q(
        124,
        "Een goedgekeurd bochtaanwijzer is een instrument waarvan de werking gebaseerd is op:",
        "een gyroscoop",
        "een endoscoop",
        "een stethoscoop",
        "a",
      ),
      q(
        125,
        'Als de "naald" van de bochtaanwijzer op 0 staat, dan',
        "blijft de voorligging, zelf onder invloed van drift, onveranderd",
        "is de voorligging 000° of Noord",
        "blijft de vaart onveranderd",
        "a",
      ),
      q(
        126,
        'Je wenst te "keren" of 180° van koers te veranderen. Hiervoor stuur je "BB 60° / min". Hoelang zal je manoeuvre in theorie duren?',
        "60 seconden",
        "120 seconden",
        "180 seconden",
        "c",
      ),
      q(
        127,
        "Een spitse ton zonder reflector zal men het best in beeld waarnemen",
        "vóórstroom varend",
        "tegenstroom varend",
        "vóór- of tegenstroom varend, er is geen onderscheid",
        "b",
      ),
      q(
        128,
        "Welke draaizin geeft de bochtaanwijzer aan van een schip dat deinst (achteruit vaart) en waarvan het achterschip SB intrekt?",
        "BB",
        "SB",
        "Nul",
        "a",
      ),
      q(
        129,
        "Welke informatie verschaft de bochtaanwijzer ons?",
        "Richting en afstand",
        "Draaizin en draaihoek",
        "Hoeksnelheid en draaizin",
        "c",
      ),
      q(
        130,
        "Hoeveel moet men de echo's van golven onderdrukken?",
        "Tot de laatste golf onderdrukt is",
        "Tot nog steeds enkele, niet storende, golvenecho's in beeld blijven",
        "De golvenonderdrukker gebruik je beter helemaal niet",
        "b",
      ),
      q(
        131,
        "Welke middelen gebruik je best om na te gaan of je een schip al dan niet oploopt?",
        'De knop "Long / Short pulse"',
        'De "VRM" of de vaste afstandsringen',
        'De "Enchance" toets',
        "b",
      ),
      q(
        132,
        "Hoeveel bedraagt de reflectiewaarde van een radarreflector?",
        "Circa 5 vierkante meter",
        "Circa 10 vierkante meter",
        "Circa 15 vierkante meter",
        "b",
      ),
      q(
        133,
        "Hoeveel tijd zal je schip theoretisch nodig hebben om een bocht van 90° te maken als je 20° / min stuurt op je bochtaanwijzer?",
        "3 minuten",
        "4,5 minuten",
        "6 minuten",
        "b",
      ),
      q(
        134,
        "Als hoogspanningskabels schuin over de vaarweg zijn gespannen terwijl zij aan BB korter bij de scanner gelegen zijn dan aan SB, dan:",
        "zal de ware echo van de kabels zich bewegen van BB naar SB",
        "zal de ware echo van de kabels zich bewegen van SB naar BB",
        "zal de ware echo van de kabels niet in beeld verschijnen",
        "a",
      ),
      q(
        135,
        "Als hoogspanningskabels schuin over de vaarweg zijn gespannen terwijl zij aan SB korter bij de scanner gelegen zijn dan aan BB, dan:",
        "zal de ware echo van de kabels zich bewegen van BB naar SB",
        "zal de ware echo van de kabels zich bewegen van SB naar BB",
        "zal de ware echo van de kabels niet in beeld verschijnen",
        "b",
      ),
      q(
        136,
        "De ware echo van een hoogspanningskabel beweegt in beeld van BB naar SB. In welke richting moeten we van koers veranderen opdat de echo recht in de koersflits zou blijven?",
        "Naar BB",
        "Naar SB",
        "Dit is niet realiseerbaar met een koerswijziging",
        "a",
      ),
      q(
        137,
        'Van een hoogspanningskabel die loodrecht over de vaarweg is gespannen krijg je "steeds" een ware echo in beeld',
        "Deze bewering is juist",
        "Deze bewering is fout",
        "Deze bewering is deels juist deels fout",
        "b",
      ),
      q(
        138,
        "Wat stel je vaak vast bij het naderen van een spoorbrug?",
        "Een meervoud aan ware echo's veroorzaakt door de elektriciteit",
        "Een overvloed aan meervoudige echo's veroorzaakt door de brugconstructie",
        "De afwezigheid van reflectoren gezien de doorvaartopening meestal voldoende duidelijk te onderscheiden is",
        "b",
      ),
      q(139, "De meeste golvenecho's zie je steeds aan:", "de lijzijde", "de loefzijde", "lager wal", "b"),
      q(
        140,
        "Is het mogelijk zelf de minimum reikwijdte te bepalen van zijn radartoestel?",
        "Ja, door langzaam korter bij de kade te komen en via de VRM vast te stellen vanaf welke afstand de kade plots uit beeld verdwijnt",
        "Neen, dit is onmogelijk",
        "Men kan dit nagaan op de technische gegevens die door de fabrikant werden verstrekt",
        "a",
      ),
      q(
        141,
        'Waarvoor dient de regelknop "Gain"?',
        "Om meer helderheid te geven",
        "Om meer versterking te geven",
        "Om een betere afstemming te geven",
        "b",
      ),
      q(
        142,
        'Waarvoor dient de regelknop "Brilliance"?',
        "Om meer helderheid te geven",
        "Om meer versterking te geven",
        "Om een betere afstemming te geven",
        "a",
      ),
      q(
        143,
        'Waarvoor dient de regelknop "Tune"?',
        "Om meer helderheid te geven",
        "Om meer versterking te geven",
        "Om een betere afstemming te geven",
        "c",
      ),
      q(
        144,
        'Wat gebeurt er als we de drukknop "trails" inschakelen?',
        "Dan vergroot men de echo's waardoor ze beter zichtbaar worden",
        "Dan krijgen de echo's een spoor achter zich dat de relatieve beweging aangeeft",
        "Dan wordt de zeilstreep uitgeschakeld",
        "b",
      ),
      q(
        145,
        "Welke knop druk je in als je storende echo's, in de vorm van kromme spaken, in beeld krijgt?",
        "HM of SHM (Heading Marker of Suppressed Heading Marker)",
        "ENCHANCE",
        "IR (Interference Rejector)",
        "c",
      ),
      q(
        146,
        'Kan je steeds een keuze maken tussen "Long Pulse" en "Short Pulse"?',
        "Neen, daar deze slechts bruikbaar is binnen de kortere schaalbereiken",
        "Neen, daar deze slechts bruikbaar is binnen de langere schaalbereiken",
        "Ja, beide pulslengte zijn bruikbaar bij elk soort schaalbereik",
        "b",
      ),
      q(
        147,
        'De afkorting "EBL" staat voor:',
        "Electronic Border Line",
        "Electronic Base Line",
        "Electronic Bearing Line",
        "c",
      ),
      q(
        148,
        'Bij het gebruik van de "Tune" knop letten we er steeds op dat:',
        "de tune of afstemmingsindicator zoveel mogelijk naar rechts is gedraaid",
        "zoveel mogelijk centraal staat",
        "de indicator zoveer mogelijk uitwijking vertoont",
        "c",
      ),
      q(
        149,
        "Schaalbereik vergroten of verkleinen doen we met:",
        'de "Ring" knop',
        'de "Off" knop',
        'de "Range" knop',
        "c",
      ),
      q(
        150,
        "Is het mogelijk de vaste ringen uit te schakelen?",
        'Ja, met de "Ring" knop',
        "Nee, dit is niet mogelijk",
        'Ja, met de "Range" knop',
        "a",
      ),
    ],
  },
  {
    id: "set4",
    name: "Reeks 4",
    description: "",
    questions: [
      q(
        151,
        "Bij het maken van een peiling mogen we het volgende stellen:",
        "de aflezing op de rand van ons scherm is steeds juist",
        "de digitale aflezing is steeds juist",
        "in een klassiek radarbeeld kan men peilen met gedecentreerd beeld zonder het risico te lopen om een foutieve aflezing te maken op de rand van het beeldscherm",
        "b",
      ),
      qWithImage(
        152,
        "Geef de betekenis van volgende knop:",
        "het toestel staat op OFF",
        "het toestel staat op ON",
        "het toestel staat op STAND – BY",
        "a",
        "/images/vraag-152.png",
      ),
      qWithImage(
        153,
        "Geef de betekenis van volgende knop:",
        "het toestel staat op OFF",
        "het toestel staat op ON",
        "het toestel staat op STAND – BY",
        "b",
        "/images/vraag-153.png",
      ),
      qWithImage(
        154,
        "Geef de betekenis van volgende knop:",
        "het toestel staat op OFF",
        "het toestel staat op ON",
        "het toestel staat op STAND – BY",
        "c",
        "/images/vraag-154.png",
      ),
      q(
        155,
        "Als het toestel op ON staat",
        "dan werkt de radar niet en krijgen de scanner of het beeldscherm geen stroom",
        "dan krijgen de scanner en het beeldscherm stroom en warmen op",
        "dan is het toestel in bedrijf, het zenden en ontvangen is bezig",
        "c",
      ),
      q(
        156,
        "Als het toestel op OFF staat",
        "dan werkt de radar niet en krijgen de scanner of het beeldscherm geen stroom",
        "dan krijgen de scanner en het beeldscherm stroom en warmen op",
        "dan is het toestel in bedrijf, het zenden en ontvangen is bezig",
        "a",
      ),
      q(
        157,
        "Als het toestel op STAND-BY staat",
        "dan werkt de radar niet en krijgen de scanner of het beeldscherm geen stroom",
        "dan krijgen de scanner en het beeldscherm stroom en warmen op",
        "dan is het toestel in bedrijf, het zenden en ontvangen is bezig",
        "b",
      ),
      qWithImage(158, "Dit symbool staat voor:", "brilliance", "range", "panel", "a", "/images/vraag-158.png"),
      qWithImage(159, "Dit symbool staat voor:", "brilliance", "range", "panel", "b", "/images/vraag-159.png"),
      qWithImage(160, "Dit symbool staat voor:", "brilliance", "range", "panel", "c", "/images/vraag-160.png"),
      q(
        161,
        "Het doel van de brilliance is",
        "op oudere toestellen de helderheid van het videobeeld, op rasterscan de instelling van het raster",
        "op oudere toestellen het rooster negatief maken, op rasterscan de helderheid van het videobeeld",
        'op rasterscan toestellen het negatief maken van het rooster, hierdoor komt het toestel in een "lektoestand"',
        "b",
      ),
      qWithImage(
        162,
        "Met deze knop stel je",
        "de zender af op de ontvanger",
        "de lengte van de impuls in",
        "de ontvanger af op de zender",
        "c",
        "/images/vraag-162.png",
      ),
      qWithImage(
        163,
        "Met deze knop stel je",
        "de zender af op de ontvanger",
        "de lengte van de impuls in",
        "de ontvanger af op de zender",
        "b",
        "/images/vraag-163.png",
      ),
      q(
        164,
        "Hoe wordt de TUNING ingesteld",
        'door het toestel in de zogenaamde "lektoestand" te brengen',
        "door zowel aan de BRILLIANCE als de TUNING in wijzerzin te draaien",
        "door zoveel mogelijk blokjes te vullen of het gebeurt automatisch",
        "c",
      ),
      q(
        165,
        '"Ruis" aan de rand van het scherm wijst op:',
        "teveel aan GAIN, dit wordt opgelost door in tegenwijzerzin (CCW) te draaien",
        "te weinig aan GAIN, dit wordt opgelost door in wijzerzin (CW) te draaien",
        "teveel BRILLIANCE, dit wordt opgelost door in tegenwijzerzin (CCW) te draaien",
        "a",
      ),
      qWithImage(
        166,
        "Met deze knop regelt men",
        "de onderdrukking van regen",
        "de versterking van de echo's",
        "de onderdrukking van golven",
        "b",
        "/images/vraag-166.png",
      ),
      qWithImage(
        167,
        "Met deze knop regelt men",
        "de onderdrukking van regen",
        "de versterking van de echo's",
        "de onderdrukking van golven",
        "c",
        "/images/vraag-167.png",
      ),
      qWithImage(
        168,
        "Met deze knop regelt men",
        "de onderdrukking van regen",
        "de versterking van de echo's",
        "de onderdrukking van golven",
        "a",
        "/images/vraag-168.png",
      ),
      q(
        169,
        "Op moderne rasterscan toestellen worden",
        "GAIN en TUNING als fijnafstemming gebruikt",
        "SHORT PULSE en LONG PULSE als fijnafstemming gebruikt",
        "SEA CLUTTER en RAIN CLUTTER als fijnafstemming gebruikt",
        "c",
      ),
      q(
        170,
        "Bij het wijzigen van de RANGE",
        "wordt de tijdbasis van de zaagtandgenerator, de repetentie, de pulslengte en vaste ringen gewijzigd",
        "wordt de variabele ring, de elektronische peilingslijn, de repetentie en de vaste ringen gewijzigd",
        "wordt de tijdbasis van zaagtandgenerator, de helderheid en de versterking van het beeld gewijzigd",
        "a",
      ),
      qWithImage(
        171,
        "Als dit symbool zichtbaar is",
        "staat het toestel in True-motion presentatie",
        "staat het toestel in North-up presentatie",
        "staat het toestel in Ship's head-up presentatie",
        "b",
        "/images/vraag-171.png",
      ),
      qWithImage(
        172,
        "Als dit symbool zichtbaar is",
        "staat het toestel in True-motion presentatie",
        "staat het toestel in North-up presentatie",
        "staat het toestel in Ship's head-up presentatie",
        "c",
        "/images/vraag-172.png",
      ),
      q(
        173,
        "De EBL gebruikt men",
        "om afstand tot een voorwerp te meten",
        "om evenwijdig met de oever te blijven varen",
        "om een peiling van een voorwerp te nemen",
        "c",
      ),
      q(
        174,
        "De VRM gebruikt men",
        "om afstand tot een voorwerp te meten",
        "om evenwijdig met de oever te blijven varen",
        "om een peiling van een voorwerp te nemen",
        "a",
      ),
      q(
        175,
        "Bij het afstellen van het toestel dient",
        "men zeer omzichtig om te springen met de SHORT en LONG PULSE",
        "men zeer omzichtig om te springen met de RAIN en SEA CLUTTER",
        "men zeer omzichtig om te springen met de EBL, VRM, HL OFF en RANGE",
        "b",
      ),
      q(
        176,
        'Als men op radar vaart betekent: "Relatieve koers"',
        "de beweging welk vaste voorwerpen maken over het scherm",
        "de beweging van alle echo's waargenomen op het scherm",
        "de beweging welk bewegende voorwerpen maken over het scherm",
        "c",
      ),
      q(
        177,
        'Als men op radar vaart betekent: "Relatieve beweging"',
        "de beweging welk vaste voorwerpen maken over het scherm",
        "de beweging van alle echo's waargenomen op het scherm",
        "de beweging welk bewegende voorwerpen maken over het scherm",
        "a",
      ),
      q(
        178,
        "De beweging samengesteld uit Rv en v van het eigen schip, Rv en v van het waargenomen schip",
        'noemt men "Relatieve koers"',
        'noemt men "Relatieve beweging"',
        'noemt men "Relatief radarbeeld"',
        "a",
      ),
      q(
        179,
        "Als het schip over bakboord draait, dan",
        "bewegen de echo's van vaste voorwerpen over bakboord over het scherm",
        "bewegen de echo's van varende en vaste voorwerpen over stuurboord over het scherm",
        "bewegen de echo's van vaste voorwerpen over stuurboord over het scherm",
        "c",
      ),
      q(
        180,
        'Als men de "Relatieve koers" denkbeeldig verlengd',
        "kan men uitmaken of dit een aanvaringskoers is of niet",
        "kan men zelden uitmaken of dit een aanvaringskoers is",
        "is het altijd een aanvaringskoers",
        "a",
      ),
      q(
        181,
        "Om de afstand van één graad te bepalen maken we gebruik van volgende formule:",
        "straal X straal X Pi gedeeld door 360",
        "straal X straal X 360 gedeeld door Pi",
        "straal + straal X Pi gedeeld door 360",
        "c",
      ),
      q(
        182,
        "Het schaalbereik is 500 meter, hoeveel bedraagt de lengte aan de rand als de peiling 5° is?",
        "33 meter",
        "44 meter",
        "55 meter",
        "b",
      ),
      q(
        183,
        "Grote sprongen van waargenomen echo's op het scherm betekend",
        "kleine naderingssnelheid",
        "grote werkelijke snelheid van de tegenligger",
        "grote naderingssnelheid",
        "c",
      ),
      q(
        184,
        "Kleine sprongen van waargenomen echo's op het scherm betekend",
        "kleine naderingssnelheid",
        "kleine werkelijke snelheid van de tegenligger",
        "grote naderingssnelheid",
        "a",
      ),
      q(
        185,
        "In een ship's head-up presentatie",
        "is de ware koers en snelheid van naderende schepen uit te maken",
        "is de ware koers uit te maken van naderende schepen maar de snelheid niet",
        "is de ware koers en snelheid van naderende schepen nooit uit te maken",
        "c",
      ),
      q(
        186,
        "Bij het aanzetten van het toestel dient",
        "men er zich van te vergewissen dat de antenne vrij kan ronddraaien",
        "men er zich van te vergewissen dat niemand in de buurt van het scherm staat",
        "men er zich van te vergewissen dat de atlas of kaart in de buurt ligt",
        "a",
      ),
      q(
        187,
        "Bij het varen op radar dient",
        "men geen wacht buiten op te stellen",
        "men er zich van te vergewissen dat niemand in de buurt van het scherm staat",
        "men een kaart of atlas in de buurt te hebben",
        "c",
      ),
      q(
        188,
        "Bij een tweemansbesturing",
        "is de roerganger dezelfde persoon als de radarwaarnemer en worden er geen bevelen gegeven",
        "is de radarwaarnemer de schipper, maar geeft de roerganger korte en duidelijke bevelen",
        "is de radarwaarnemer de schipper, hij geeft korte en duidelijke bevelen",
        "c",
      ),
      qWithImageAnswers(189, "Om het beeld te centreren / decentreren maakt men gebruik van volgende knop:", "c", {
        a: "/images/antwoord-a-189-en-190.png",
        b: "/images/antwoord-b-189-en-190.png",
        c: "/images/antwoord-c-189-en-190.png",
      }),
      qWithImageAnswers(190, "Om de koersflits te onderdrukken maakt men gebruik van volgende knop:", "b", {
        a: "/images/antwoord-a-189-en-190.png",
        b: "/images/antwoord-b-189-en-190.png",
        c: "/images/antwoord-c-189-en-190.png",
      }),
      qWithImageAnswers(191, "Interference rejector wordt vaak als volg afgebeeld:", "a", {
        a: "/images/antwoord-a-191-en-192-en-193.png",
        b: "/images/antwoord-b-191-en-192-en-193.png",
        c: "/images/antwoord-c-191-en-192-en-193.png",
      }),
      qWithImageAnswers(192, "Electronic bearing line wordt vaak als volg afgebeeld:", "c", {
        a: "/images/antwoord-a-191-en-192-en-193.png",
        b: "/images/antwoord-b-191-en-192-en-193.png",
        c: "/images/antwoord-c-191-en-192-en-193.png",
      }),
      qWithImageAnswers(193, "Variable range marker wordt vaak als volg afgebeeld:", "b", {
        a: "/images/antwoord-a-191-en-192-en-193.png",
        b: "/images/antwoord-b-191-en-192-en-193.png",
        c: "/images/antwoord-c-191-en-192-en-193.png",
      }),
      q(
        194,
        "Radar is de afkorting voor",
        "Radio detection and ranging",
        "Random detection and searching",
        "Radio and detection for ranging",
        "a",
      ),
      q(
        195,
        "Een radartoestel laat toe",
        "om door middel van een bundel, de voorwerpen te zien en te plaatsen in het beeldscherm",
        "om door middel van een computerprogramma, voorwerpen te ontdekken en op de juiste plaats af te beelden",
        "om door middel van radiogolven, voorwerpen op te sporen en te lokaliseren",
        "c",
      ),
      q(
        196,
        "Een radartoestel maakt gebruik van golven welke",
        "300 000 000 km/s afleggen",
        "300 000 km/s afleggen",
        "300 000 m/s afleggen",
        "b",
      ),
      q(
        197,
        "Frequentie is",
        "de afstand tussen twee golftoppen of twee golfdalen, het wordt uitgedrukt in m of cm",
        "de hoogte van de golf bij vertrek uit het toestel, hoe meer energie hoe groter de amplitude",
        "het aantal golven opgewekt per seconde, het wordt uitgedrukt in Hz",
        "c",
      ),
      q(
        198,
        "Golflengte is",
        "de afstand tussen twee golftoppen of twee golfdalen, het wordt uitgedrukt in m of cm",
        "de hoogte van de golf bij vertrek uit het toestel, hoe meer energie hoe groter de amplitude",
        "het aantal golven opgewekt per seconde, het wordt uitgedrukt in Hz",
        "a",
      ),
      q(
        199,
        "Amplitude is",
        "de afstand tussen twee golftoppen of twee golfdalen, het wordt uitgedrukt in m of cm",
        "de hoogte van de golf bij vertrek uit het toestel, hoe meer energie hoe groter de amplitude",
        "het aantal golven opgewekt per seconde, het wordt uitgedrukt in Hz",
        "b",
      ),
      q(
        200,
        'De radar aan boord van de "THEMIS II" heeft een frequentie van 9.410 MHz. Hoeveel bedraagt de golflengte?',
        "3,18 cm",
        "2,75 cm",
        "3,00 cm",
        "a",
      ),
    ],
  },
  {
    id: "set5",
    name: "Reeks 5",
    description: "",
    questions: [
      q(201, 'De radar aan boord van de "THEMIS II" zend uit in de', "S-band", "X-band", "X- en S-band", "b"),
      q(
        202,
        "Radar is een engelse afkorting en staat voor:",
        "Radio detection and ranging",
        "Rasterscan data recognition",
        "Radio data and ranging",
        "a",
      ),
      q(
        203,
        "De voortplantingssnelheid van de elektromagnetische golven bedraagt:",
        "300.000 m/s",
        "300.000.000 km/s",
        "300.000 km/s",
        "c",
      ),
      q(204, "Het aantal golven opgewekt per seconden noemen we:", "golflengte", "frequentie", "amplitude", "b"),
      q(
        205,
        "Een Hz (Hertz) is gelijk aan:",
        "10.000 golven per seconden",
        "1.000 golven per seconden",
        "1 golf per seconden",
        "c",
      ),
      q(206, "Frequentie X golflengte =", "amplitude", "voortplantingssnelheid", "golfperiode", "b"),
      q(
        207,
        "De frequentie van een radar bedraagt 9.410 MHz. Hoeveel bedraagt de golflengte?",
        "3,18 cm",
        "2,75 cm",
        "3,00 cm",
        "a",
      ),
      q(
        208,
        "De afstand tussen de plaats van uitzending en een waargenomen voorwerp, kan vastgesteld worden door:",
        "de afstand tussen het voorwerp te meten en delen door twee",
        "de tijd te meten tussen zendimpuls en delen door twee",
        "door de tijd die verstreek tussen uitzenden van een impuls en het binnenkomen van een echo te meten, delen door twee en vermenigvuldigen met 300.000.000 m/s.",
        "c",
      ),
      q(
        209,
        "De tijd tussen uitzenden en ontvangen van de elektromagnetische golf bedraagt 60 μs. Hoeveel bedraagt de afstand?",
        "18.000 m.",
        "9.000 m.",
        "900 m.",
        "b",
      ),
      q(
        210,
        "Een binnenvaart radar erkend door de Rijnvaart inspectie zendt uit in de:",
        "S band",
        "Q band",
        "X band",
        "c",
      ),
      q(211, "Een seconde is gelijk aan:", "100.000 μs", "1.000.000 μs", "1.000 μs", "b"),
      q(212, "Een Mega Hertz (MHz) is gelijk aan:", "1.000.000 Hz", "100.000 Hz", "1.000 Hz", "a"),
      q(
        213,
        "De hoofdtrillingskring:",
        "Zorgt dat de hoge spanningen omgezet worden in radargolven",
        "Is de klok van de radar en geeft op regelmatige tijdstippen spanningstoten",
        "Zet de spanningsstoten om in zeer hoge spanning gedurende de ganse zendtijd",
        "b",
      ),
      q(
        214,
        "De magnetron:",
        "Zorgt dat de hoge spanningen omgezet worden in radargolven",
        "Is de klok van de radar en geeft op regelmatige tijdstippen spanningstoten",
        "Zet de spanningsstoten om in zeer hoge spanning gedurende de ganse zendtijd",
        "a",
      ),
      q(
        215,
        "De modulator:",
        "Zorgt dat de hoge spanningen omgezet worden in radargolven",
        "Is de klok van de radar en geeft op regelmatige tijdstippen spanningstoten",
        "Zet de spanningsstoten om in zeer hoge spanning gedurende de ganse zendtijd",
        "c",
      ),
      q(
        216,
        "Het zendgedeelte van een radar bestaat uit volgende onderdelen:",
        "De magnetron, de elektronische schakelaar, de zaagtandstroom generator en de antenne",
        "De antenne, de versterker, de magnetron, de elektronische schakelaar.",
        "De modulator, de magnetron, de hoofdtrillingskring, de antenne en de elektronische schakelaar.",
        "c",
      ),
      q(
        217,
        "De elektronische schakelaar:",
        "Sluit het ontvangst gedeelte af, gedurende de ganse zendtijd",
        "Sluit het ontvangst gedeelte niet af, gedurende de ganse zendtijd",
        "Sluit het ontvangst gedeelte soms af, gedurende de ganse zendtijd",
        "a",
      ),
      q(
        218,
        "Het afstandsonderscheidingsvermogen van een radar is gelijk aan:",
        "Tweemaal de impulslengte",
        "De helft van de impulslengte",
        "Gelijk aan de impulslengte",
        "b",
      ),
      q(
        219,
        "De horizontale bundelbreedte van een binnenvaart radar bedraagt:",
        "Meer dan 2°",
        "Maximaal 1,2°",
        "Minder dan 0,5°",
        "b",
      ),
      q(
        220,
        "Het horizontaal onderscheidingsvermogen is het best bij een bundelbreedte van:",
        "Minder of gelijk aan 1°",
        "Meer dan 2°",
        "Is in beide gevallen hetzelfde",
        "a",
      ),
      q(
        221,
        "De verticale bundelbreedte van een binnenvaartradar bedraagt:",
        "Maximaal 1,2°",
        "Tussen de 20° à 25°",
        "Is onbegrensd",
        "b",
      ),
      q(
        222,
        "De repetentie van het toestel wordt bepaald door:",
        "De modulator",
        "De golflengte",
        "De hoofdtrillingskring",
        "c",
      ),
      q(
        223,
        "Het ontvangstgedeelte van de radar bestaat uit:",
        "De zaagtandstroomgenerator, de antenne, de modulator, de elektronische schakelaar en de beeldbuis",
        "De beeldbuis, de antenne, de elektronische schakelaar, de zaagtandstroomgenerator, de versterker en de Gunn oscillator",
        "De Gunn oscillator, de antenne, de elektronische schakelaar, de zaagtandstroomgenerator en de versterker",
        "b",
      ),
      q(
        224,
        "Met een radar kan men:",
        "Het soort en uitzicht kennen van omringende voorwerpen",
        "De peiling en afstand kennen van omringende voorwerpen",
        "De afstand en het uitzicht kennen van omringende voorwerpen",
        "b",
      ),
      q(
        225,
        "De impulslengte wordt vergroot:",
        "Door de zendtijd in te korten",
        "Door de zendtijd te verlengen",
        "Door de zendtijd niet te veranderen",
        "b",
      ),
      q(
        226,
        "Als aan de tuning gedraaid wordt dan stellen we:",
        "De zender en de ontvanger af",
        "De zender af op de ontvanger",
        "De ontvanger af op de zender",
        "c",
      ),
      q(
        227,
        "Als men van short pulse overschakelt naar long pulse moeten voorwerpen in radiale richting om apart op het scherm te komen:",
        "Verder van elkaar liggen",
        "Korter bij elkaar liggen",
        "Op dezelfde afstand van elkaar liggen.",
        "a",
      ),
      q(228, "De middenfrequentie wordt afgestemd door:", "De gain", "De tuning", "De gain en de tuning", "b"),
      q(
        229,
        "Binnenkomende echo's worden:",
        "Rechtstreeks versterkt",
        "De middenfrequentie wordt versterkt",
        "Ze worden allebei versterkt",
        "b",
      ),
      q(
        230,
        "Op een binnenvaart radar is de middenfrequentie:",
        "Gelijk aan 10.000 MHz",
        "Tussen de 30 en 10.000 MHz",
        "Gelijk aan 30 MHz",
        "c",
      ),
      q(
        231,
        "Om versterkt te worden:",
        "Moet de middenfrequentie juist afgestemd zijn",
        "Heeft het geen belang of de middenfrequentie afgestemd is",
        "Kan men de middenfrequentie afstemmen",
        "a",
      ),
      q(
        232,
        "Om een voorwerp op de juiste afstand in beeld te brengen maakt de radar gebruik van:",
        "Een computer programma",
        "De zaagtandstroomgenerator",
        "Een computer programma en de zaagtandstroomgenerator",
        "b",
      ),
      q(
        233,
        "Het bereik van de radar wordt bepaald door:",
        "De hoogte van de antenne, het geobserveerde voorwerp, het schaalbereik en de atmosferische omstandigheden,",
        "De hoogte van de antenne, het geobserveerde voorwerp, het piekvermogen van de zender en de atmosferische omstandigheden",
        "De hoogte van de antenne, het geobserveerde voorwerp, het piekvermogen van de zender, het schaalbereik en de atmosferische omstandigheden",
        "b",
      ),
      q(
        234,
        "Hoe hoger de antenne geplaatst is:",
        "Hoe kleiner het bereik",
        "Verandert niets aan het bereik",
        "Hoe groter het bereik",
        "c",
      ),
      q(
        235,
        "Als men het schaalbereik wijzigt, wijzigt men ook:",
        "Het computerprogramma",
        "Het computerprogramma en de tijdbasis van de zaagtandstroomgenerator",
        "De tijdbasis van de zaagtandstroomgenerator",
        "c",
      ),
      q(
        236,
        "Om de binnenkomende echo's te versterken gaat men de gain knop:",
        "In wijzerzin draaien",
        "In tegen wijzerzin draaien",
        "Niet draaien",
        "a",
      ),
      q(
        237,
        "De knoppen rain-clutter en sea-clutter gebruikt men om te:",
        "Onderdrukken",
        "Versterken",
        "Versterken en te onderdrukken",
        "a",
      ),
      q(
        238,
        "Om een goede echo te verkrijgen moet het voorwerp:",
        "Goed geleidend zijn, grote rechte vlakken bezitten, een aspect van 80° en een bepaalde oppervlakteruwheid hebben.",
        "Goed geleidend zijn, grote rechte vlakken bezitten, een aspect van 90° en een bepaalde oppervlakteruwheid hebben.",
        "Goed geleidend zijn, kleine ronde vlakken bezitten, een aspect van 90 ° en een bepaalde oppervlakteruwheid hebben.",
        "b",
      ),
      q(
        239,
        "Bij regen gaat men:",
        "De rain-clutter in tegen wijzerzin draaien om een beetje te onderdrukken",
        "De rain-clutter in wijzerzin draaien om een beetje te onderdrukken",
        "De rain-clutter niet aan draaien om een beetje te onderdrukken",
        "b",
      ),
      q(
        240,
        "De weerkaatsing op een kaaimuur geeft een goed ontvangen echo als:",
        "Het aspect groter is dan 90°",
        "Het aspect kleiner is dan 90°",
        "Het aspect gelijk is aan 90°",
        "c",
      ),
      q(
        241,
        "De blinde afstand van een radar is:",
        "Groter dan de helft van de impulslengte",
        "Kleiner dan de helft van de impulslengte",
        "Gelijk aan de helft van de impulslengte",
        "a",
      ),
      q(
        242,
        "De Azimutale vergroting is:",
        "Groter dan de horizontale bundelhoek",
        "Kleiner dan de horizontale bundelhoek",
        "Gelijk aan de horizontale bundelhoek",
        "c",
      ),
      q(
        243,
        "Bij windkracht 5 Bft. is de windrichting op het radarscherm:",
        "Te bepalen",
        "Niet te bepalen",
        "Misschien te bepalen",
        "a",
      ),
      q(
        244,
        "Op de peilers van een brug staan radarreflectoren geplaatst op een afstand van 12,5 meters,",
        "De echo van deze reflectoren komen afgescheiden van de brug, op het scherm",
        "De echo van deze reflectoren komen niet afgescheiden van de brug, op het scherm",
        "De echo van deze reflectoren komen misschien afgescheiden van de brug, op het scherm",
        "a",
      ),
      q(
        245,
        "Een valse echo",
        "Verdwijnt even snel als hij is opgekomen",
        "Blijft steeds in beeld",
        "Verschijnt nooit in beeld",
        "a",
      ),
      q(
        246,
        'Onder het begrip "relatieve koers" wordt verstaan: de richting en zin waarin de echo\'s van andere voorwerpen zich over het scherm verplaatsen. Hierdoor is de ware koers en snelheid van deze voorwerpen te bepalen',
        "Hierdoor is de ware koers en snelheid van deze voorwerpen niet te bepalen",
        "Hierdoor is de ware koers en snelheid van deze voorwerpen misschien te bepalen",
        "b",
      ),
      q(
        247,
        "De relatieve koers wordt beïnvloedt door:",
        "De ware koers en vaart van het eigen schip",
        "De ware koers en vaart van het andere schip",
        "De ware koers en vaart van het eigen schip en de ware koers en vaart van het andere schip",
        "c",
      ),
      q(
        248,
        "De bochtaanwijzer geeft de volgende informatie:",
        "De hoeksnelheid en de draaizin van de beweging van het schip",
        "De hoeksnelheid van de beweging van het schip",
        "De draaizin van de beweging van het schip",
        "a",
      ),
      q(
        249,
        "De hoeksnelheid wordt uitgedrukt:",
        "In graden per seconde",
        "In graden per minuut",
        "In graden per uur",
        "b",
      ),
      q(
        250,
        "Bij gelijke vaart:",
        "Hoe kleiner de hoeksnelheid, hoe scherper de bocht",
        "Hoe groter de hoeksnelheid, hoe scherper de bocht",
        "Hoe groter de hoeksnelheid, hoe ruimer de bocht",
        "b",
      ),
      q(
        251,
        "Bij gelijke hoeksnelheid:",
        "Hoe groter de snelheid van het schip, hoe scherper de bocht",
        "Hoe groter de snelheid van het schip, hoe ruimer de bocht",
        "Hoe kleiner de snelheid van het schip, hoe ruimer de bocht",
        "b",
      ),
    ],
  },
]

export function getQuestionsByIds(ids: number[]): Question[] {
  const allQuestions = questionSets.flatMap((set) => set.questions)
  return ids.map((id) => allQuestions.find((q) => q.id === id)).filter((q): q is Question => q !== undefined)
}
